sudo: required
services:
  - docker

before_install:
  - docker build -t jgdomine/docker-react -f Dockerfile.dev .

script:
  - docker run jgdomine/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-909229216481"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"